# Generated by Django 4.0.2 on 2022-02-08 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('theme', models.CharField(choices=[('Alcohol', 'Alcohol'), ('Antiques', 'Antiques'), ('Art', 'Art'), ('Models', 'Models'), ('Money', 'Money'), ('Non-artificial objects', 'Non-artificial objects'), ('Printed products', 'Printed products'), ('Souvenirs', 'Souvenirs'), ('Stamps', 'Stamps'), ('Weapons and military', 'Weapons and military'), ('Other', 'Other')], default='Other', max_length=30, verbose_name='Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'db_table': 'item_collection',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.itemcollection')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'item',
            },
        ),
    ]
